program: '/home/aditya/Code/interpretable_ml/project/train.py'
project: 'tomato-disease-classification'
name: 'sweeptomatoes'
method: 'bayes'
metric:
  name: 'val_loss'
  goal: 'minimize'
parameters:
  seed: 
    values: [0]
  root_dir: 
    values: ['/home/aditya/Code/interpretable_ml/project']
  dataset: 
    values: ['CCMT']
  model: 
    values: ['resnet']
  num_classes: 
    values: [5]
  batch_size: 
    values: [32]
  num_epochs:
    values: [15]
  dropout: 
    min: 0.1
    max: 0.4
    distribution: 'uniform'
  lr: 
    min: 1e-6
    max: 1e-3
    distribution: 'uniform'
  weight_decay: 
    min: 1e-6
    max: 1e-3
    distribution: 'uniform'
  display_loss_interval: 
    values: [0.1]
  val_interval: 
    values: [0.5]

command:
  - python3
  - ${program}
  - ${args_no_hyphens}